language: rust
matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
  include:
    # - os: linux
    #   rust: stable
    # - os: linux
    #   rust: beta
    # - os: linux
    #   rust: nightly
    - os: osx
      rust: stable
    - os: osx
      rust: beta
    - os: osx
      rust: nightly
script:
  - cargo doc --verbose --no-deps
  - cargo build --verbose
  - cargo test --verbose
